### ISSUE TITLE
Routes

### ISSUE THREAD

**Issue by Axkaban** [Mikky2/project-3-the-scoop#2]
Great work on setting up your [comments routes](https://github.com/Mikky2/project-3-the-scoop/blob/master/server.js#L34-L46)

It might have felt simple, but as you start learning express it will make more sense how the functions you have created link with the routes object, since it will be more of an argument in a get() method it will be more visually connected that when the api is reached at the endpoint, like '/comments' it will trigger the function `createComment()` in our case right now, the server is also checking if there is also a call for the property POST of the object, and that will call the function.

**Comment by Mikky2** [comment]
Thank you. learning express seems to be fun already!
