### ISSUE TITLE
Functions

### ISSUE THREAD

**Issue by Axkaban** [Mikky2/project-3-the-scoop#3]
If compared they are really alike to the article functions, but only certain details change. That is common in server side programming, sometimes it is even helpful to create reusable functions,  like one that will work for articles and comments the same way and vary depending on the arguments passed. For example the delete function for [comments](https://github.com/Mikky2/project-3-the-scoop/blob/master/server.js#L118) and the delete function for [articles](https://github.com/Mikky2/project-3-the-scoop/blob/master/server.js#L141) you can bundle the code after the first three to four lines into it's own function and just check for comments or articles, and adjust if it is `articleCommentsId` or `userCommentsId`

Now, you do not have to do this, it is just something to keep in mind for the future, answering the question : **_How can I simplify this more?_**

**Comment by Mikky2** [comment]
Ok I got you on that...
