### ISSUE TITLE
response.body

### ISSUE THREAD

**Issue by Axkaban** [Mikky2/project-3-the-scoop#4]
One more thing that you can do for simplification is taking advantage of [object destructuring](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#Object_destructuring), 
in this case if you renamed [savedComment](https://github.com/Mikky2/project-3-the-scoop/blob/master/server.js#L99) in your updateComment function as comment, you could simply pass the variable in the parenthesis when assigning it to response.body, there javascript will use the variable as the property and its value as the value of the property. This can be done for all the response.body assignments in your functions.
`response.body = {comment};`
It mainly cleans up your code, for easy reading.

**Comment by Mikky2** [comment]
Thank you. I agree with you on that. I will implement that, It will simplify the code
