### ISSUE TITLE
.yaml file db

### ISSUE THREAD

**Issue by Axkaban** [Mikky2/project-3-the-scoop#5]
Very smart to implement [fs](https://github.com/Mikky2/project-3-the-scoop/blob/master/server.js#L2)
It is a great method to read and write files which is already part of node!
Great work using yaml as well, your [load and save](https://github.com/Mikky2/project-3-the-scoop/blob/master/server.js#L49-L61) functions are simple and very efficient.

**Comment by Mikky2** [comment]
Thank you
