### ISSUE TITLE
overall

### ISSUE THREAD

**Issue by Axkaban** [Mikky2/project-3-the-scoop#6]
Grade: **Met requirements and surpassed expectations**

A total 200 OK! Congratulations on a great job.

The only thing I would say you need to implement is comments throughout your code. In my case I know what you are supposed to do, what the code should kind of look like and what the result should be, but if it is someone foreign to it that has to work with you or someone that will  like to use your code, it is helpful to have an explanation on what does what and sometimes how, as well as some reasons behind choices. Having comments is also a very good practice for you to remember what you've done before.

Best of luck!

**Comment by Mikky2** [comment]
Thank you so much for taking time to review my project. Your comments and suggestions are well appreciated. I will work on implementing comments throughout my code. I know it's useful and helpful, i haven't been practicing that.
